server {
  listen 80;
  server_name localhost;

  gzip on;

  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-XSS-Protection "1; mode=block" always;
  add_header X-Content-Type-Options "nosniff" always;

  # Редирект со старых доменов на новые

  # if ($host = hseillustration.burgstg.ru) {
  #   return 301 https://hsedesign.burgstg.ru/illustration;
  # }
  # if ($host = hseillustration.ru) {
  #   return 301 https://hsedesign.ru/illustration;
  # }
  # Файлы для верификации поисковиков
  location /yandex_a56ff020e5f802dd.html {
    try_files $uri /yandex_a56ff020e5f802dd.html;
  }
  location /google7b3ed415a963f6b9.html {
    try_files $uri /google7b3ed415a963f6b9.html;
  }


  location / {
    etag on;

    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }

  location /assets/ {
    root /usr/share/nginx/html;
    etag on;
    # Добавляем кеширование, в бесконечность. Так как у каждого файла есть хеш, но может баговать с REPLACE_ если env меняются без пересборки
    add_header Cache-Control "public, max-age=31536000, immutable";
  }

  # Отключаем кеширование для файлов env-*.js в папке assets
  location ~ ^/assets/env-.*\.js$ {
    root /usr/share/nginx/html;

    expires -1;
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    add_header Pragma "no-cache";
  }

  client_max_body_size 20M;
  proxy_read_timeout 30s;
  proxy_connect_timeout 30s;
  proxy_send_timeout 30s;

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}

